//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaRecibo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolizaRecibo()
        {
            this.PolizaCuotas = new HashSet<PolizaCuota>();
        }
    
        public int id { get; set; }
        public decimal NroRecibo { get; set; }
        public System.DateTime FechaRecibo { get; set; }
        public System.TimeSpan HoraRecibo { get; set; }
        public int idUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaCuota> PolizaCuotas { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
