//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poliza()
        {
            this.Poliza1 = new HashSet<Poliza>();
            this.PolizaHijoes = new HashSet<PolizaHijo>();
            this.PolizaMedidaSeguridads = new HashSet<PolizaMedidaSeguridad>();
            this.PolizaRenovacions = new HashSet<PolizaRenovacion>();
            this.PolizaValorFactorAutoscorings = new HashSet<PolizaValorFactorAutoscoring>();
            this.PolizaCuotas = new HashSet<PolizaCuota>();
        }

        public Poliza(DTO.dto_poliza dtoPoliza)
        {
            NroPolizaSuc = 0001; //Hardcode
            NroPolizaSec = dtoPoliza.NroPolizaSec;
            datosVehiculo = dtoPoliza.Marca + "-" + dtoPoliza.Modelo + "-" + dtoPoliza.AñoVehiculo;
            valorAsegurado = dtoPoliza.Suma_Asegurada;
            nroMotor = dtoPoliza.NroMotor;
            nroChasis = dtoPoliza.NroChasis;
            patente = dtoPoliza.Patente;
            kmPorAño = dtoPoliza.KmPorAño;
            nroSiniestros = dtoPoliza.Nro_Siniestros;
            fechaInicioVigencia = dtoPoliza.FechaInicioVigencia;
            fechaFinVigencia = fechaInicioVigencia.AddDays(180);
            importeDerechoEmision = dtoPoliza.DerechoEmision;
            importePremio = dtoPoliza.Premio;
            importeDescuento = dtoPoliza.ImporteDescuento;
            importeTotal = dtoPoliza.Monto_Abonar;
            idPolizaAnterior = null;

            this.PolizaHijoes = new HashSet<PolizaHijo>();
            this.Poliza1 = new HashSet<Poliza>();
            this.PolizaCuotas = new HashSet<PolizaCuota>();
            this.PolizaMedidaSeguridads = new HashSet<PolizaMedidaSeguridad>();
            this.PolizaRenovacions = new HashSet<PolizaRenovacion>();
            this.PolizaValorFactorAutoscorings = new HashSet<PolizaValorFactorAutoscoring>();
        }
        public int id { get; set; }
        public decimal NroPolizaSuc { get; set; }
        public decimal NroPoliza { get; set; }
        public decimal NroPolizaSec { get; set; }
        public int idTipoCobertura { get; set; }
        public int idLocalidad { get; set; }
        public int idVehiculo { get; set; }
        public int idCliente { get; set; }
        public string datosVehiculo { get; set; }
        public decimal valorAsegurado { get; set; }
        public string nroMotor { get; set; }
        public string nroChasis { get; set; }
        public string patente { get; set; }
        public decimal kmPorAño { get; set; }
        public decimal nroSiniestros { get; set; }
        public System.DateTime fechaInicioVigencia { get; set; }
        public System.DateTime fechaFinVigencia { get; set; }
        public Nullable<decimal> importePremio { get; set; }
        public Nullable<decimal> importeDescuento { get; set; }
        public Nullable<decimal> importeDerechoEmision { get; set; }
        public Nullable<decimal> importeTotal { get; set; }
        public Nullable<int> idPolizaAnterior { get; set; }
        public int idEstadoPoliza { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoPoliza EstadoPoliza { get; set; }
        public virtual Localidad Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poliza> Poliza1 { get; set; }
        public virtual Poliza Poliza2 { get; set; }
        public virtual TipoCobertura TipoCobertura { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaHijo> PolizaHijoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaMedidaSeguridad> PolizaMedidaSeguridads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaRenovacion> PolizaRenovacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaValorFactorAutoscoring> PolizaValorFactorAutoscorings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaCuota> PolizaCuotas { get; set; }
    }
}
