//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaRenovacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolizaRenovacion()
        {
            this.PolizaRenovacionHijoes = new HashSet<PolizaRenovacionHijo>();
        }
    
        public int id { get; set; }
        public int idPoliza { get; set; }
        public decimal NroPolizaSec { get; set; }
        public int idTipoCobertura { get; set; }
        public int idLocalidad { get; set; }
        public int idVehiculo { get; set; }
        public decimal valorAsegurado { get; set; }
        public string nroMotor { get; set; }
        public string nroChasis { get; set; }
        public string patente { get; set; }
        public decimal kmPorAño { get; set; }
        public decimal nroSiniestros { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual Poliza Poliza { get; set; }
        public virtual TipoCobertura TipoCobertura { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaRenovacionHijo> PolizaRenovacionHijoes { get; set; }
    }
}
