//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Cliente
    {
        public int id { get; set; }
        public decimal NroCliente { get; set; }
        public decimal AñoRegistro { get; set; }
        public string CorreoElectronico { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> nroDocumento { get; set; }
        public Nullable<decimal> nroCuil { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string calle { get; set; }
        public Nullable<decimal> numero { get; set; }
        public string piso { get; set; }
        public string departamento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public string Pais { get; set; }
        public Nullable<decimal> codpostal { get; set; }
        public string Localidad { get; set; }
        public string nombreTipoDocumento { get; set; }
        public string NombreSituacionIVA { get; set; }
        public string Provincia { get; set; }
        public string Profesion { get; set; }
        public string EstadoCliente { get; set; }
    }
}
