//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Localidad
    {
        public int idLocalidad { get; set; }
        public string nombre { get; set; }
        public decimal codpostal { get; set; }
        public string Provincia { get; set; }
        public string Pais { get; set; }
    }
}
