//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorFactorAutoScoring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValorFactorAutoScoring()
        {
            this.ValorFactorAutoScoringHists = new HashSet<ValorFactorAutoScoringHist>();
        }
    
        public int id { get; set; }
        public int idGrupoFactorAutoscoring { get; set; }
        public int CodFactorItem { get; set; }
        public decimal valorPorcentual { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual GrupoFactorAutoScoring GrupoFactorAutoScoring { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValorFactorAutoScoringHist> ValorFactorAutoScoringHists { get; set; }
    }
}
